### ISSUE TITLE
Setup guide missing dependencies

### ISSUE THREAD

**Issue by fosJoddie** [Map-A-Droid/MAD-docs#3]
Ubuntu setup guide is missing segment about installing tesseract and possibly to use `sudo apt install python3-opencv` instead of the pip ocr requirement 

- at least I needed to install these manually to get quest scanning running

**Comment by muckelba** [comment]
Thats either fixed already or was never a problem. I don't know anymore 😂 

https://github.com/Map-A-Droid/MAD-docs/blob/master/installation/1.getting-started.md#L153
