### ISSUE TITLE
Add a list of common acronyms

### ISSUE THREAD

**Issue by reedy** [Map-A-Droid/MAD-docs#50]
Where would be a good place to add a list of common acronyms? The FAQ? Or a new section?

**Comment by muckelba** [comment]
New section sounds good

**Comment by reedy** [comment]
I'll have a poke later on after setting up a dev environment locally. Can't quite so easily/lazily just edit multiple files via the GitHub web interface

Any particular preference on section naming? Does Glossary work for you?

**Comment by muckelba** [comment]
Yes, Glossary is fine :) 

((btw, theres a makefile for a automatic local dev webserver, but i assume you are already aware of that :D ))

**Comment by reedy** [comment]
> ((btw, theres a makefile for a automatic local dev webserver, but i assume you are already aware of that :D ))

Ja. That's what I was meaning by a local dev env. I know it's not much more than a few dependancies and stuff (so probably venv for ease) as per https://mad-docs.readthedocs.io/en/latest/#contributing-to-this-wiki, but still needs doing

**Comment by reedy** [comment]
Started doing this on https://github.com/reedy/MAD-docs/tree/glossary

Will turn it into a PR when it's a bit more fleshed out
