### ISSUE TITLE
Makefile auto build dir hard coded

### ISSUE THREAD

**Issue by reedy** [Map-A-Droid/MAD-docs#55]
Is there any reason the Makefile's auto build dir is hard coded as `_build`? Any reason I can't swap it to "$(BUILDDIR)" like the other usages?

Same for the source dir

**Comment by muckelba** [comment]
`_build` is getting ignored in the .gitignore file, thats why

**Comment by reedy** [comment]
But even if you change the directory for the other build modes... You're not going to be presumably committing those either?

**Comment by muckelba** [comment]
Well, you are probably right. If someone is changing that dir, he's are aware of potentially committing it, yes.
