### ISSUE TITLE
Link "security section" at "Further steps" does not work

### ISSUE THREAD

**Issue by to-fr** [Map-A-Droid/MAD-docs#69]
Installation -> Manual Installation -> Further steps -> security section

says:

        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|

**Comment by reedy** [comment]
https://mad-docs.readthedocs.io/en/latest/installation/manual/#further-steps

Link is to https://mad-docs.readthedocs.io/en/latest/installation/manual/sec_security, should be to https://mad-docs.readthedocs.io/en/latest/installation/security/

**Comment by reedy** [comment]
Issue can be closed as fixed by #71
