### ISSUE TITLE
Information on how to update MADmin

### ISSUE THREAD

**Issue by Fireobirdy** [Map-A-Droid/MAD-docs#77]
Documentation misses the information how to update madmin.

**Comment by acocalypso** [comment]
git pull?

**Comment by reedy** [comment]
> git pull?

Heh. I guess there's a little variance depending on type of install... And "you should stop MAD first"...

**Comment by acocalypso** [comment]
tbh I never stop mad First.
I Just do git pull and restart the service :D

**Comment by Fireobirdy** [comment]
Thanks!
